#pragma once

#define MAP_PROGRESS_STEP 7
#define MISSILE_PROGRESS_STEP 7

#define REFRESH_MAP 10
#define REFRESH_MISSILES 10
#define REFRESH_PLAYERS 8

#define REFRESH_WAIT_MESSAGE 200

#define JOIN_TIMEOUT 3000

#define MOVE_TIME 10